export const FETCH_BOOKS_PENDING = 'FETCH_BOOKS_PENDING'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED'

export const FETCH_BOOK_PENDING = 'FETCH_BOOK_PENDING'
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS'
export const FETCH_BOOK_FAILED = 'FETCH_BOOK_FAILED'

export const SAVE_BOOK_REVIEW_PENDING = 'SAVE_BOOK_REVIEW_PENDING'
export const SAVE_BOOK_REVIEW_SUCCESS = 'SAVE_BOOK_REVIEW_SUCCESS'
export const SAVE_BOOK_REVIEW_FAILED = 'SAVE_BOOK_REVIEW_FAILED'

export const SAVE_BOOK_PENDING = 'SAVE_BOOK_PENDING'
export const SAVE_BOOK_SUCCESS = 'SAVE_BOOK_SUCCESS'
export const SAVE_BOOK_FAILED =  'SAVE_BOOK_FAILED'